### ISSUE TITLE
 The 'Pods-Runner' target has frameworks with conflicting names: webrtc.xcframework.

### ISSUE THREAD

**Issue by dkliss** [jitsi/jitsi-meet-flutter-sdk#1]
Hi,  I am getting error below, if I use flutter_webrtc: ^0.9.36 &  jitsi-meet-flutter-sdk together in Pubspec.Yaml.

"Target has frameworks with conflicting names: webrtc.xcframework."

I am already using flutter_webrtc: ^0.9.36  in my pubspec,yaml and when I add jitsi-meet-flutter-sdk, it creates two same POD frame works:
One is within : PodsJitsiWebRTC/WebRTC.xcframework.
And second is reated at POD/WebRTC-SDK/WebRTC.xcframework.

This does not happen if I use the example application because example application only uses jitsi-meet-flutter-sdk & not flutter_webrtc: ^0.9.36. 

Also, flutter pub get does not work, if I use below. 

jitsi_meet_flutter_sdk: '^0.1.0'

I was wondering if there is a way for both  flutter_webrtc: ^0.9.36 &  jitsi-meet-flutter-sdk to work together without duplicating webrtc.xcframework.". Thanks!

**Comment by saghul** [comment]
There is nothing we can do about it, our SDK uses WebRTC and so does the other plugin, I'm afraid they cannot be used together.
