### ISSUE TITLE
Stripe compatibility error: E/AndroidRuntime(14968): FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by cyclone-pk** [jitsi/jitsi-meet-flutter-sdk#16]
when ever I try to join meeting app crash.

I found the problem I am using FlutterFragmentActivity which is require. by. stripe.
and jisti require FlutterActivity so. how can I fix this.

E/AndroidRuntime(14968): FATAL EXCEPTION: main
E/AndroidRuntime(14968): Process: com.pixatroniclab.happylife, PID: 14968
E/AndroidRuntime(14968): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~AfiUZhXeUbxpptFOytG25A==/com.pixatroniclab.happylife-9DbsHFFDJlzdkkDCwnDtiw==/base.apk!classes12.dex)
E/AndroidRuntime(14968): 	at com.facebook.react.ReactAndroidHWInputDeviceHelper.<clinit>(ReactAndroidHWInputDeviceHelper.java:25)
E/AndroidRuntime(14968): 	at com.facebook.react.ReactRootView.<init>(ReactRootView.java:102)
E/AndroidRuntime(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:180)
E/AndroidRuntime(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:223)
E/AndroidRuntime(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:156)
E/AndroidRuntime(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/AndroidRuntime(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/AndroidRuntime(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/AndroidRuntime(14968): 	at org.jitsi.jitsi_meet_flutter_sdk.WrapperJitsiMeetActivity.onCreate(WrapperJitsiMeetActivity.kt:35)
E/AndroidRuntime(14968): 	at android.app.Activity.performCreate(Activity.java:8054)
E/AndroidRuntime(14968): 	at android.app.Activity.performCreate(Activity.java:8034)
E/AndroidRuntime(14968): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
E/AndroidRuntime(14968): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
E/AndroidRuntime(14968): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
E/AndroidRuntime(14968): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime(14968): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(14968): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(14968): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
E/AndroidRuntime(14968): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(14968): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(14968): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(14968): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime(14968): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14968): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(14968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/JitsiMeetSDK(14968): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(14968): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~AfiUZhXeUbxpptFOytG25A==/com.pixatroniclab.happylife-9DbsHFFDJlzdkkDCwnDtiw==/base.apk!classes12.dex)
E/JitsiMeetSDK(14968): 	at com.facebook.react.ReactAndroidHWInputDeviceHelper.<clinit>(ReactAndroidHWInputDeviceHelper.java:25)
E/JitsiMeetSDK(14968): 	at com.facebook.react.ReactRootView.<init>(ReactRootView.java:102)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:180)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:223)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:156)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/JitsiMeetSDK(14968): 	at org.jitsi.jitsi_meet_flutter_sdk.WrapperJitsiMeetActivity.onCreate(WrapperJitsiMeetActivity.kt:35)
E/JitsiMeetSDK(14968): 	at android.app.Activity.performCreate(Activity.java:8054)
E/JitsiMeetSDK(14968): 	at android.app.Activity.performCreate(Activity.java:8034)
E/JitsiMeetSDK(14968): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
E/JitsiMeetSDK(14968): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/JitsiMeetSDK(14968): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(14968): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
E/JitsiMeetSDK(14968): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(14968): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(14968): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/JitsiMeetSDK(14968): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(14968): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(14968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/JitsiMeetSDK(14968): 
E/JitsiMeetSDK(14968): java.lang.NoSuchMethodError: No static method builder()Lcom/facebook/react/common/MapBuilder$Builder; in class Lcom/facebook/react/common/MapBuilder; or its super classes (declaration of 'com.facebook.react.common.MapBuilder' appears in /data/app/~~AfiUZhXeUbxpptFOytG25A==/com.pixatroniclab.happylife-9DbsHFFDJlzdkkDCwnDtiw==/base.apk!classes12.dex)
E/JitsiMeetSDK(14968): 	at com.facebook.react.ReactAndroidHWInputDeviceHelper.<clinit>(ReactAndroidHWInputDeviceHelper.java:25)
E/JitsiMeetSDK(14968): 	at com.facebook.react.ReactRootView.<init>(ReactRootView.java:102)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.createReactRootView(JitsiMeetView.java:180)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.setProps(JitsiMeetView.java:223)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetView.join(JitsiMeetView.java:156)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.join(JitsiMeetActivity.java:174)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.initialize(JitsiMeetActivity.java:220)
E/JitsiMeetSDK(14968): 	at org.jitsi.meet.sdk.JitsiMeetActivity.onCreate(JitsiMeetActivity.java:109)
E/JitsiMeetSDK(14968): 	at org.jitsi.jitsi_meet_flutter_sdk.WrapperJitsiMeetActivity.onCreate(WrapperJitsiMeetActivity.kt:35)
E/JitsiMeetSDK(14968): 	at android.app.Activity.performCreate(Activity.java:8054)
E/JitsiMeetSDK(14968): 	at android.app.Activity.performCreate(Activity.java:8034)
E/JitsiMeetSDK(14968): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
E/JitsiMeetSDK(14968): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/JitsiMeetSDK(14968): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/JitsiMeetSDK(14968): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
E/JitsiMeetSDK(14968): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(14968): 	at android.os.Looper.loopOnce(Looper.java:201)
E/JitsiMeetSDK(14968): 	at android.os.Looper.loop(Looper.java:288)
E/JitsiMeetSDK(14968): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/JitsiMeetSDK(14968): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(14968): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/JitsiMeetSDK(14968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/Process (14968): Sending signal. PID: 14968 SIG: 9

**Comment by saghul** [comment]
Closing in favor of https://github.com/jitsi/jitsi-meet-flutter-sdk/issues/37 which has a lengthier conversation.
