### ISSUE TITLE
Join button not working on real android phone.

### ISSUE THREAD

**Issue by altabmw01** [jitsi/jitsi-meet-flutter-sdk#18]
I have installed sdk example folder on my Android Studio and it's working well. After building apk and install on my real android device join button not working. After clicking on join button it's not open the meeting and redirect on main page.

**Comment by nhtdev1** [comment]
I got the same.

**Comment by kietdev123** [comment]
@gabiborlea i have same problems and here is my logs.
[log_jisti_android.txt](https://github.com/user-attachments/files/16344522/log_jisti_android.txt)
![image](https://github.com/user-attachments/assets/45bf9806-b57d-4221-826a-a0a25eb79d54)

**Comment by kietdev123** [comment]
In my case, i use proguard-rules.pro in wrong way, make sure you follow this file.
[https://raw.githubusercontent.com/gunschu/jitsi_meet/master/jitsi_meet/example/android/app/proguard-rules.pro](url)
