### ISSUE TITLE
Any plan for supporting desktop apps? (macOS/Windows/Linux)

### ISSUE THREAD

**Issue by huskyjp** [jitsi/jitsi-meet-flutter-sdk#2]
I know you guys provide electron sdk for desktop application, but I am wondering if you have a roadmap to support the desktop applications in this flutter sdk? (because the flutter desktop is already stable and I am currently building desktop based video conference app with flutter)

**Comment by saghul** [comment]
We have no plans for that. Our only support in the desktop is web browsers, and Electron it's kind of one. Having a Flutter version of that would be just a WebView. If someone wants to contribute a patch I think we'd take it, but we are not going to build a native desktop client for Jitsi Meet.

**Comment by saghul** [comment]
[](url)

**Comment by Junr-Studio** [comment]
@saghul  still no plan for supporting Desktop SDK ? Or a workaround ?

**Comment by saghul** [comment]
No plans, no. You could use a webview.

**Comment by Junr-Studio** [comment]
@saghul Thanks for you prompt answer. Webview compatibility with desktop app is very poor. And the iFrame have really not the same integration level than the SDK though.

**Comment by saghul** [comment]
Yes, that's correct, but creating a full desktop app is not something we have plans to do, sorry.
