### ISSUE TITLE
Hide polls in Jitsi Chat in Flutter with jitsi_meet_flutter_sdk: ^0.1.7 ??

### ISSUE THREAD

**Issue by Valere3162** [jitsi/jitsi-meet-flutter-sdk#22]
I want to know how to hide polls in Jitsi Chat in Flutter with jitsi_meet_flutter_sdk: ^0.1.7

We are getting Polls tab under Chat but we couldnt find out the way to rid of Polls tab from chat window.

Is anyone has any idea how we can hide Polls from chat window

**Comment by gabiborlea** [comment]
Hey! Sorry for the late reply. Please try setting `disablePolls: true` in the configOverwrites.
