### ISSUE TITLE
some ConfigOverwrite Options don't work

### ISSUE THREAD

**Issue by ugmlr** [jitsi/jitsi-meet-flutter-sdk#29]
Hi, i was trying to hide a few of the buttons in the UI (when video calling) & have found the easiest way to do so would be to use the toolButtons Option in the configOverride unfortunately this doesn't work for me. This is my Code:

```
configOverrides: {
        'toolbarButtons': [ //should work, but doesn't right now
        'camera',
              'hangup',
              'toggle-camera',
        ],
}
```
Just in case i was doing something wrong when writing it.
I also have a few featureFlags enabled, in case this is the problem, but i have already tried disabling all of them and i can still see other buttons, for example the participants pane button

**Comment by shabanov-krl** [comment]
@gabiborlea prejoinConfig.hideExtraJoinButtons also not work for mobile? i want to hide `no-audio` join button
