### ISSUE TITLE
I am facing issue " failed for task ':app:mergeSuperbrainsDebugNativeLibs'. "  while running the app with android device.

### ISSUE THREAD

**Issue by yash-pietech** [jitsi/jitsi-meet-flutter-sdk#34]
I added jitsi_meet_flutter_sdk package in our project and try to run the app with android emulators and it is giving me issue below mwntion.

* What went wrong:
Execution failed for task ':app:mergeSuperbrainsDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libc++_shared.so' from inputs:
      - /Users/yash/.gradle/caches/transforms-3/33d29e1c66569354021d5859c62139c8/transformed/jetified-arm64_v8a_debug-1.0.0-74d16627b940bb15e50891f82cad6c3e3465bd6d/arm64-v8a/libc++_shared.so
      - /Users/yash/.gradle/caches/transforms-3/e51881bfb75863deb0337baa54459c7c/transformed/jetified-react-native-0.69.12/jni/arm64-v8a/libc++_shared.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
     

### Flutter Doctor Output

`[✓] Flutter (Channel stable, 3.16.3, on macOS 13.3.1 22E772610a darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.0)
[✓] Connected device (4 available)
[✓] Network resources
`

Here is the screenshot of error I am facing , would you please check and help me to resolved this issue
<img width="1068" alt="image" src="https://github.com/jitsi/jitsi-meet-flutter-sdk/assets/126047746/2429d16c-990f-485f-84d4-3d4718ba9b5a">
 please let me know if you need more info on this issue .

**Comment by shubh-damodar** [comment]
What is the workaround? @yash-pietech
