### ISSUE TITLE
IOS Screen Share is not working

### ISSUE THREAD

**Issue by Bruno-Megaleios** [jitsi/jitsi-meet-flutter-sdk#36]
In the IOS, the screen share is not working, the app its not appearing in record menu. I tryed the example App too.

![image](https://github.com/jitsi/jitsi-meet-flutter-sdk/assets/86243188/1fb40d08-ad8e-4b1b-85ff-4778c49d0b02)

**Comment by LumiProj** [comment]
I am experiencing the same issue, but I am aware that no one is managing this project with the level of professionalism it requires.

**Comment by gabiborlea** [comment]
Hello! You have to add a broadcast extension to your app, you can find the steps here: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/#screen-sharing-integration.
