### ISSUE TITLE
unable to join without moderator? 

### ISSUE THREAD

**Issue by SamarthSerpentCS** [jitsi/jitsi-meet-flutter-sdk#42]
![Screenshot_20240108_125029](https://github.com/jitsi/jitsi-meet-flutter-sdk/assets/50228977/900d265c-c095-4883-8854-7c63a2daea18)

unable to join without moderator? 

when i joined 2 devices with same ropom and and different user name then show alert unable to join without moderator.
when i joined with web and login with google then works fine. 
i find token inside JitsiMeetConferenceOptions, but how to add in token for mobile app?

This is my code

 var options = JitsiMeetConferenceOptions(
      serverURL: "https://meet.jit.si/",
      room: "ROOM12345678",
      configOverrides: {
        "startWithAudioMuted": false,
        "startWithVideoMuted": false,
        "subject": "Lipitori"
      },
      featureFlags: {
        "unsaferoomwarning.enabled": false,
        "ios.screensharing.enabled": true
      },
      userInfo: JitsiMeetUserInfo(
          displayName: "ABC",
          email: "abc@gmail.com",
          avatar:
              "https://cdn.pixabay.com/photo/2016/11/18/23/38/child-1837375_640.png"),
    );

**Comment by Calinteodor** [comment]
The server url that you are using has authentication and you cannot join a meeting without a moderator.

**Comment by navidanchitrali** [comment]
@Calinteodor  how to authenticate user with the server URL mentioned above, or is it possible to authenticate before the message appear?

**Comment by saghul** [comment]
You cannot control authentication on meet.jit.si because that's a deployment we maintain. You should have your own deployment and then you can choose what type of auth you want.

**Comment by Qasim4w** [comment]
yes i also also face jitsi crash after release how to solve it
