### ISSUE TITLE
Conflict between flutter_webrtc and jitsi_meet_flutter_sdk plugins

### ISSUE THREAD

**Issue by Vinayak006** [jitsi/jitsi-meet-flutter-sdk#43]
Description:

I'm encountering a conflict between the flutter_webrtc and jitsi_meet_flutter_sdk plugins in my Flutter project. Both plugins seem to have dependencies that are causing conflicts, specifically with classes like org.webrtc.voiceengine.WebRtcAudioUtils.

Steps to Reproduce:

- Add both flutter_webrtc and jitsi_meet_flutter_sdk plugins to a Flutter project.
- Attempt to build the project.

Environment:

Flutter version: 3.16.3
Operating System: android

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class org.webrtc.AddIceObserver found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
     Duplicate class org.webrtc.AndroidVideoDecoder found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)

**Comment by saghul** [comment]
Unfortunately that is not something we can fix.

Both packages depend on org.webrtc and each needs a different build.
