### ISSUE TITLE
Issues in Flutter WebRTC and Jitsi Meet integration.

### ISSUE THREAD

**Issue by Vinayak006** [jitsi/jitsi-meet-flutter-sdk#44]
Jitsi Meet and Flutter WebRTC are experiencing compatibility issues when utilized within the same project.

To Reproduce:
Include both flutter_webrtc and jitsi_meet_flutter_sdk packages.
Build a project

 Duplicate class org.webrtc.TextureBufferImpl$2 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.TextureBufferImpl$RefCountMonitor found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$1 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$1CaughtException found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$1Result found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$2 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$3 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$4 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$BlockingOperation found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.ThreadUtils$ThreadChecker found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.TimestampAligner found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.TurnCustomizer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoCapturer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoCodecInfo found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoCodecMimeType found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoCodecStatus found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoDecoder found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoDecoder$Callback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoDecoder$DecodeInfo found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoDecoder$Settings found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoDecoderFactory found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoDecoderFallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoDecoderWrapper found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$BitrateAllocation found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$Callback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$Capabilities found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$CodecSpecificInfo found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$CodecSpecificInfoAV1 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$CodecSpecificInfoH264 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$CodecSpecificInfoVP8 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$CodecSpecificInfoVP9 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$EncodeInfo found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$EncoderInfo found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$RateControlParameters found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$ResolutionBitrateLimits found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$ScalingSettings found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoder$Settings found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoderFactory found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoderFactory$VideoEncoderSelector found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoderFallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoEncoderWrapper found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFileRenderer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFileRenderer$1 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrame found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrame$Buffer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrame$I420Buffer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrame$TextureBuffer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrame$TextureBuffer$Type found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrameBufferType found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrameDrawer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrameDrawer$1 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoFrameDrawer$YuvUploader found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoProcessor found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoProcessor$FrameAdaptationParameters found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoSink found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoSource found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoSource$1 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoSource$AspectRatio found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.VideoTrack found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.WebRtcClassLoader found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.WrappedNativeI420Buffer found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.WrappedNativeVideoDecoder found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.WrappedNativeVideoEncoder found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.YuvConverter found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.YuvConverter$ShaderCallbacks found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.YuvHelper found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.AudioDeviceModule found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$AudioRecordErrorCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$AudioRecordStartErrorCode found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$AudioRecordStateCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$AudioSamples found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$AudioTrackErrorCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$AudioTrackStartErrorCode found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$AudioTrackStateCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$Builder found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.JavaAudioDeviceModule$SamplesReadyCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.LowLatencyAudioBufferManager found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.VolumeLogger found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.VolumeLogger$LogVolumeTask found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioEffects found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioManager found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioRecord found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioRecord$1 found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioRecord$AudioRecordThread found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioTrack found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioTrack$AudioTrackThread found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.audio.WebRtcAudioUtils found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.BuildInfo found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioEffects found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioManager found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioManager$VolumeLogger found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioManager$VolumeLogger$LogVolumeTask found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioRecord found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioRecord$AudioRecordStartErrorCode found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioRecord$AudioRecordThread found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioRecord$AudioSamples found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioRecord$WebRtcAudioRecordErrorCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioRecord$WebRtcAudioRecordSamplesReadyCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioTrack found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioTrack$AudioTrackStartErrorCode found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioTrack$AudioTrackThread found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioTrack$ErrorCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioTrack$WebRtcAudioTrackErrorCallback found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)
Running Gradle task 'assembleDebug'...                            
     Duplicate class org.webrtc.voiceengine.WebRtcAudioUtils found in modules jetified-android-114.5735.08.1-runtime (io.github.webrtc-sdk:android:114.5735.08.1) and jetified-webrtc-111.0.1-runtime (org.jitsi:webrtc:111.0.1)

**Comment by saghul** [comment]
I already replied here: https://github.com/jitsi/jitsi-meet-flutter-sdk/issues/43

Please don't duplicate issues.
