### ISSUE TITLE
App Android Crash When start meeting 

### ISSUE THREAD

**Issue by conan1150** [jitsi/jitsi-meet-flutter-sdk#54]
Crash when release mode.

tested on 
- Emulator Android 32
- Xiaomi
- Samsung
- Huawei
- BlueStacks

Plugin version 0.1.2 - 0.2.2

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/apollo_global/apollo:10/QKQ1.200419.002/V12.0.11.0.QJDMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-04-01 12:51:25+0700
pid: 6063, tid: 6282, name: create_react_co  >>> com.abc.xyz <<<
uid: 11191
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  000000000000188a  x2  0000000000000006  x3  0000007476b7dfd0
    x4  fefeff7375b70f17  x5  fefeff7375b70f17  x6  fefeff7375b70f17  x7  7f7f7f7f7fff7f7f
    x8  00000000000000f0  x9  7b0e750fa7993c95  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 00000075be5c88c8  x17 00000075be5a4550  x18 0000007475156000  x19 00000000000017af
    x20 000000000000188a  x21 00000000ffffffff  x22 0000007471367aea  x23 0000007476b81018
    x24 0000000000000015  x25 00000074b87caa80  x26 00000074dbda1ac0  x27 00000074dbda1ac0
    x28 00000074715dc3d4  x29 0000007476b7e070
    sp  0000007476b7dfb0  lr  00000075be5550c4  pc  00000075be5550f0

backtrace:
      #00 pc 00000000000830f0  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 6dc18c350dc6bdab66bd0af0dcfd6e4c)
      #01 pc 00000000003fc624  /data/app/com.abc.xyz -vZh0AWcItW8oDHLm5o7arg==/base.apk!libjingle_peerconnection_so.so (offset 0x1616000) (BuildId: 72783674f1d34510)

**Comment by TimmyChannel** [comment]
@conan1150 how did you solve this problem?
