### ISSUE TITLE
Issue using jitsi_meet_flutter_sdk with flutter_stripe

### ISSUE THREAD

**Issue by Korefey** [jitsi/jitsi-meet-flutter-sdk#57]
I have already using flutter_stripe: ^10.1.1
When I try to use jitsi_meet_flutter_sdk getting following issue.
Can you help me to solve it?

`ERROR: /Users/user/mobile-app/build/stripe_android/intermediates/runtime_library_classes_jar/release/bundleLibRuntimeToJarRelease/classes.jar: R8: Type com.facebook.react.bridge.ActivityEventListener is defined multiple times: /Users/user/mobile-app/build/stripe_android/intermediates/runtime_library_classes_jar/release/bundleLibRuntimeToJarRelease/classes.jar:com/facebook/react/bridge/ActivityEventListener.class, /Users/user/.gradle/caches/transforms-3/4f7519734dc5512afee8b9f92593aeb4/transformed/jetified-react-android-0.72.9-release-runtime.jar:com/facebook/react/bridge/ActivityEventListener.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete, origin: /Users/user/mobile-app/build/stripe_android/intermediates/runtime_library_classes_jar/release/bundleLibRuntimeToJarRelease/classes.jar:com/facebook/react/bridge/ActivityEventListener.class
`

**Comment by saghul** [comment]
This is a known issue: https://github.com/jitsi/jitsi-meet-flutter-sdk/issues/37
