### ISSUE TITLE
The conference has not yet started because no moderators have yet arrived. If you'd like to become a moderator please log-in. Otherwise, please wait.

### ISSUE THREAD

**Issue by yash3135** [jitsi/jitsi-meet-flutter-sdk#59]
### **Facing This Issue any one have knowledge how to fix this**
![WhatsApp Image 2024-05-02 at 01 57 51_1f38397f](https://github.com/jitsi/jitsi-meet-flutter-sdk/assets/84435147/6545adbe-0106-4b69-998a-22b00bd7d1be)

**Comment by damencho** [comment]
https://github.com/jitsi/jitsi-meet-flutter-sdk/issues/8

You can use your deployment where you control the authentication.

**Comment by yash3135** [comment]
I am using Flutter sdk so how can I do that

**Comment by damencho** [comment]
The flutter sdk is the client side SDK for which you need a backend.

You can host it by installing debian packages:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/
Or using docker:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

**Comment by damencho** [comment]
Yes, you can use the Jitsi Meet to do so.
Anything else will not align with the terms of service.
https://jitsi.org/meet-jit-si-terms-of-service/

**Comment by yash3135** [comment]
How can I get token to start meeting?
