### ISSUE TITLE
Which package should i use in production ??

### ISSUE THREAD

**Issue by jackwill99** [jitsi/jitsi-meet-flutter-sdk#6]
I found [jitsi-meet](https://pub.dev/packages/jitsi_meet) and [jitsi-meet-wrapper](https://pub.dev/packages/jitsi_meet_wrapper). Which package should i use in production and, is this official package [jitsi-meet-flutter-sdk](https://pub.dev/packages/jitsi_meet_flutter_sdk) stable now and can use in production level ?

I want to know clearly. 

Thanks.

**Comment by saghul** [comment]
We are the maintainers of https://pub.dev/packages/jitsi_meet_flutter_sdk and it's the one we recommend for production use.
