### ISSUE TITLE
Request to upgrade to the latest RNCWebView version.

### ISSUE THREAD

**Issue by TreyThomas93** [jitsi/jitsi-meet-flutter-sdk#60]
I believe upgrading to the latest version of RNCWebView will fix the issue I have been having with not being able to tap on the etherpad screen on Android device. Are you able to do this or do I need to fork? Thanks

**Comment by saghul** [comment]
What version contains a fix?

**Comment by TreyThomas93** [comment]
I am not sure on the exact version, but this [comment](https://github.com/react-native-webview/react-native-webview/issues/3400#issuecomment-2074276229) states that its fixed in the latest version.
