### ISSUE TITLE
Moderator end the meeting, but meeting still ongoing 

### ISSUE THREAD

**Issue by bunthoeun-develop** [jitsi/jitsi-meet-flutter-sdk#66]
Actual behavior: When moderator end meeting, the meeting still ongoing.
Expected behavior: When moderator end meeting, should show up two options for moderator, #1 `End meeting for all` #2 ` Leave meeting`.

https://github.com/jitsi/jitsi-meet-flutter-sdk/assets/65479486/0b220846-686a-40ec-a637-cd45b4c6578f

**Comment by saghul** [comment]
That depends on how your server is configured. By default it just leaves the meeting.

You need to enable the end conference component.

**Comment by bunthoeun-develop** [comment]
Currently, I'm using Jaas Service. Please tell me how to enable it.

**Comment by saghul** [comment]
That feature doesn't work on JaaS, you need you use an API call for it: https://developer.8x8.com/jaas/docs/webhooks-jaas-endpoints see `DESTROY_ROOM`.

Please raise a support ticker for further JaaS questions and to request we look into enabling this feature in the UI.
