### ISSUE TITLE
App Crashed

### ISSUE THREAD

**Issue by Gagandeep1408** [jitsi/jitsi-meet-flutter-sdk#7]
: Binary XML file line #12 in com.com.myAppPackage:layout/activity_jitsi_meet: Binary XML file line #12 in com.myAppPackage:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView
E/JitsiMeetSDK(29378): Caused by: android.view.InflateException: Binary XML file line #12 in com.com.myAppPackage:layout/activity_jitsi_meet: Error inflating class org.jitsi.meet.sdk.JitsiMeetView

**Comment by gabiborlea** [comment]
Doesn't seem to be on our side.

**Comment by spn107** [comment]
> Doesn't seem to be on our side.

use flutter_stripe. you will get same issue.

**Comment by saghul** [comment]
We don't know what the incompatibility problem is with that library, sorry.
