### ISSUE TITLE
need login???

### ISSUE THREAD

**Issue by abasahmed** [jitsi/jitsi-meet-flutter-sdk#8]
get this mnessage when try to join meeting:
"The conference has not yet started because no
moderators have yet arrived. If you'd like to become
a moderator please log-in. Otherwise, please wait."

The package was working for a long time but now is asking for a password or log-in
can I get help
![Screen Shot 2023-08-28 at 5 21 20 PM](https://github.com/jitsi/jitsi-meet-flutter-sdk/assets/77807738/12d5a34f-fa36-4444-80ca-a8fe8eee3450)

**Comment by gabiborlea** [comment]
Hello! Now authentication has been introduced to meet.jit.si. Check out this blog post: https://jitsi.org/blog/authentication-on-meet-jit-si/.
