### ISSUE TITLE
Streamline behaviour on iOS and Android, when joining a meeting that was already joined and is running in PiP

### ISSUE THREAD

**Issue by saibotma** [jitsi/jitsi-meet-flutter-sdk#80]
| Android | iOS |
|--------|--------|
| Enters full screen ✅| Stays in Pip ❌ |
| <video src="https://github.com/user-attachments/assets/5b48f830-6134-4184-90ea-f6c9e5b332fb"> | <video src="https://github.com/user-attachments/assets/c2cc7666-a1f9-4e10-9a29-f20bf37daa24"> | 

I'd expect the same behaviour on both platforms. More specifically, I'd expect the Android behaviour on both platforms.

**Comment by saghul** [comment]
PiP behaves differently across both platforms, alas.

On Android it's true PiP, but on iOS we are only able to offer in-app-pip.

There is likely a way to make this consistent in the sample app, and a patch woould be welcomee, but, just to set your expectations here, we will not be doing it anytime soon.
