### ISSUE TITLE
[Feature] Add the possibility to control PiP programmatically

### ISSUE THREAD

**Issue by fabiocody** [jitsi/jitsi-meet-flutter-sdk#82]
It would be nice to programmatically control the status of PiP.

From a quick look at the code, it seems feasible on iOS.
Unfortunately, I'm not familiar enough with Android to assess its feasibility there.

If anyone is interested, I'm open to collaborating on implementing this feature.

**Comment by saghul** [comment]
What do you need to do programatically?

**Comment by fabiocody** [comment]
Enter and exit PiP

**Comment by saghul** [comment]
It's not possible to exit PiP programatically on Android, only to enter it. We currently enter it automatically if the activity goes to the background, or the user can use the caret button.

What use case do you have?

**Comment by fabiocody** [comment]
Actually, for my specific use case, I only need to programmatically enter PiP.

My goal is to navigate the user to another page when they click on a custom button within Jitsi.
To achieve this, I need to enter PiP to ensure the underlying app becomes visible.
