### ISSUE TITLE
Jitsi crashes whenever i try to make an audio or video call 

### ISSUE THREAD

**Issue by Masteribrahim1** [jitsi/jitsi-meet-flutter-sdk#84]
My app crashes on release or profile mode. when i am on profile mode it gives this error 

"FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':jitsi_meet_flutter_sdk:generateProfileRFile'.
Could not resolve all files for configuration ':jitsi_meet_flutter_sdk:profileCompileClasspath'.
Could not resolve com.facebook.react:react-android:0.73.8.
Required by:
project :jitsi_meet_flutter_sdk > org.jitsi.react:jitsi-meet-sdk:10.1.2
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-amplitude:2.17.3-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-giphy:2.3.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-google-signin:10.1.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-async-storage:1.23.1-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-background-timer:2.4.1-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-calendar-events:2.2.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-community_clipboard:1.14.1-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-community_netinfo:11.1.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-default-preference:1.4.4-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-device-info:10.9.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-gesture-handler:2.18.1-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-get-random-values:1.9.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-immersive-mode:2.0.2-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-keep-awake:4.0.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-orientation-locker:1.6.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-pager-view:6.2.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-performance:5.0.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-safe-area-context:4.10.8-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-screens:3.32.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-slider:4.4.3-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-sound:0.11.2-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-splash-screen:3.3.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-svg:13.13.0-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-video:6.0.0-alpha.11-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-webrtc:124.0.4-jitsi-17848034
project :jitsi_meet_flutter_sdk > com.facebook.react:react-native-webview:13.8.7-jitsi-17848034
> No matching variant of com.facebook.react:react-android:0.73.8 was found. The consumer was configured to find an API of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.3.0', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
- Variant 'debugVariantDefaultApiPublication' capability com.facebook.react:react-android:0.73.8 declares an API of a component:
- Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
- Other compatible attributes:
- Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.0')
- Doesn't say anything about its target Java environment (preferred optimized for Android)
- Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
- Variant 'debugVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.73.8 declares a runtime of a component:
- Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
- Other compatible attributes:
- Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.0')
- Doesn't say anything about its target Java environment (preferred optimized for Android)
- Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
- Variant 'debugVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.73.8 declares a runtime of a component:
- Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
- Other compatible attributes:
- Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.0')
- Doesn't say anything about its target Java environment (preferred optimized for Android)
- Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
- Variant 'releaseVariantDefaultApiPublication' capability com.facebook.react:react-android:0.73.8 declares an API of a component:
- Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
- Other compatible attributes:
- Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.0')
- Doesn't say anything about its target Java environment (preferred optimized for Android)
- Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
- Variant 'releaseVariantDefaultRuntimePublication' capability com.facebook.react:react-android:0.73.8 declares a runtime of a component:
- Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
- Other compatible attributes:
- Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.0')
- Doesn't say anything about its target Java environment (preferred optimized for Android)
- Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')
- Variant 'releaseVariantDefaultSourcePublication' capability com.facebook.react:react-android:0.73.8 declares a runtime of a component:
- Incompatible because this component declares a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release' and the consumer needed a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'profile'
- Other compatible attributes:
- Doesn't say anything about com.android.build.api.attributes.AgpVersionAttr (required '7.3.0')
- Doesn't say anything about its target Java environment (preferred optimized for Android)
- Doesn't say anything about org.jetbrains.kotlin.platform.type (required 'androidJvm')"

**Comment by aridzan** [comment]
@Masteribrahim1 are you able to solve this problem?

**Comment by Masteribrahim1** [comment]
> @Masteribrahim1 are you able to solve this problem?

Not really, I had to look for another option, I think the problem was that I wasn't using progurad rule, kindly add that information to your documentation

**Comment by saghul** [comment]
Another user figured out how to make profile builds work until RN provides one. https://github.com/jitsi/jitsi-meet-flutter-sdk/issues/91#issuecomment-2402804171
