### ISSUE TITLE
I need jitsi BuildContext please

### ISSUE THREAD

**Issue by WidiNetkrom** [jitsi/jitsi-meet-flutter-sdk#88]

**Comment by WidiNetkrom** [comment]
I need for show dialog after jitsi callback

**Comment by saghul** [comment]
What jitsdi context?

**Comment by saghul** [comment]
Is that a Flutter thing? Jitsi will run in its own Activity, so you'd need to reorder another activity in front.

**Comment by WidiNetkrom** [comment]
> Is that a Flutter thing? Jitsi will run in its own Activity, so you'd need to reorder another activity in front.

yes currently i work with flutter.
if that is not possible, I will try other ways. Thanks

**Comment by saghul** [comment]
Sorry, I don't know what we could do to help here.
