### ISSUE TITLE
Invalid Executable. The executable 'Runner.app/Frameworks/GiphyUISDK.framework/GiphyUISDK' contains bitcode.

### ISSUE THREAD

**Issue by saibotma** [jitsi/jitsi-meet-flutter-sdk#89]
Getting this error message when trying to upload an App using this package to the App Store.
It seems like the GiphyUI SDK has bitcode enabled. Can this be disabled somehow?

**Comment by saghul** [comment]
What Xcode version are you using? Please share your Podfile.lock. This is odd, we have never run into this one!

**Comment by ihkilz** [comment]
I am also experiencing this issue. After researching, I found that it's because Xcode 16 no longer supports BITCODE. I see that the GiphyUISDK developers have released a new version to fix this.

In Podfile.lock
- Giphy version in Podfile.lock is `2.2.4`, while the latest is `2.2.11`
```
  - JitsiMeetSDK (10.2.1):
    - Giphy (= 2.2.4)
    - JitsiWebRTC (~> 124.0)
```

flutter doctor
```
[✓] Flutter (Channel stable, 3.24.3, on macOS 15.0 24A335 darwin-arm64, locale en-TH)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
```

issue:
<img width="735" alt="issue" src="https://github.com/user-attachments/assets/d08ead9c-bf5a-411f-be2d-b4f2a41d8acb">

**Comment by saghul** [comment]
Got to know!

We will update the SDK. In the meantime, use Xcode 15 as a workaround if possible.

**Comment by saghul** [comment]
Ping @Calinteodor

**Comment by bhavins13** [comment]
I am also experiencing this issue. After researching, I found that it's because Xcode 16 no longer supports BITCODE. I see that the GiphyUISDK developers have released a new version to fix this.

In Podfile.lock

Giphy version in Podfile.lock is 2.2.4, while the latest is 2.2.11
  - JitsiMeetSDK (10.2.1):
    - Giphy (= 2.2.4)
    - JitsiWebRTC (~> 124.0)

**Comment by saghul** [comment]
Yes, we will be updating out dependency for the next version of the Jitsi Meet SDK.

**Comment by muxtorovinomjon0227** [comment]
hello
I have the same problem

**Comment by saghul** [comment]
We are going to release an updated SDK soon.

**Comment by Munisbek777** [comment]
can you tell us when? can you release it today? we need it today please

**Comment by saghul** [comment]
No I can't. It's also quite rude to ask people to work for free for you, and more so on a Sunday.

You don't need it, use Xcode 15 to upload your app and the problem is avoided.

**Comment by Lukaalishi** [comment]
> We are going to release an updated SDK soon.

when ?

**Comment by Calinteodor** [comment]
> No I can't. It's also quite rude to ask people to work for free for you, and more so on a Sunday.
> 
> You don't need it, use Xcode 15 to upload your app and the problem is avoided.

Please read this carefully and take it in consideration until a new release is available. There are many important things that we are working on right now, that we also want to include. Thank you.

**Comment by thaliachitziou99** [comment]
I found a solution that works for me. I had to add this on Podfile
```
post_install do |installer|
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!

  def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    framework_path = File.join(Dir.pwd, framework_relative_path)
    command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
    puts "Stripping bitcode: #{command}"
    system(command)
  end

  framework_paths = [
    "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64_armv7/GiphyUISDK.framework/GiphyUISDK",
  ]

  framework_paths.each do |framework_relative_path|
    strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
  end

  installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
    end
end
```

**Comment by saghul** [comment]
Good one!

**Comment by erickmanovei** [comment]
> I found a solution that works for me. I had to add this on Podfile
> 
> ```
> post_install do |installer|
>   bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
> 
>   def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
>     framework_path = File.join(Dir.pwd, framework_relative_path)
>     command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
>     puts "Stripping bitcode: #{command}"
>     system(command)
>   end
> 
>   framework_paths = [
>     "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64_armv7/GiphyUISDK.framework/GiphyUISDK",
>   ]
> 
>   framework_paths.each do |framework_relative_path|
>     strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
>   end
> 
>   installer.pods_project.targets.each do |target|
>       flutter_additional_ios_build_settings(target)
>     end
> end
> ```

It didn't work for me. There is no such directory "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64_armv7/GiphyUISDK.framework/GiphyUISDK" in my project, the directories that exist are these:

framework_paths = [
    "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule",
    "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64_x86_64-maccatalyst/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule",
    "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64_x86_64-maccatalyst/GiphyUISDK.framework/Versions/A/Modules/GiphyUISDK.swiftmodule",
    "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64_x86_64-maccatalyst/GiphyUISDK.framework/Modules/GiphyUISDK.swiftmodule",
    "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64_x86_64-simulator/GiphyUISDK.framework"
  ]

I added them and it still didn't work.

**Comment by pharidali** [comment]
`post_install do |installer|
    installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end

    framework_paths = [
      "Pods/Giphy/GiphySDK/GiphyUISDK.xcframework/ios-arm64/GiphyUISDK.framework/GiphyUISDK",
    ]

    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end
end`

**Comment by Arazilabid** [comment]
i am using your latest master code and created its sdk for ios and android from visual studio

**Comment by Arazilabid** [comment]
> What SSK version are you testing? Yes this is fixed in the latest version.

Also i am using jitsi meet    https://github.com/jitsi/jitsi-meet and on it i am facing that issue

**Comment by Arazilabid** [comment]
your master code may be last month one

**Comment by Arazilabid** [comment]
And also we are having same issue on latest cocoa pod 'JitsiMeetSDK'

**Comment by saghul** [comment]
Tell me the commit or I cannot help you.

**Comment by Arazilabid** [comment]
Commit no : **ede8ae6cb94ab6cc5b2466d7280ced9b0ab42629**
Date           : **14 July**
Branch       : **Master**

**Comment by saghul** [comment]
Can you test SDK 11.4.0 wich just got released?
