### ISSUE TITLE
How to install JitSi on a VPS (Ubuntu) server for use without an internet connection ???

### ISSUE THREAD

**Issue by chegmarco1989** [jitsi/jitsi-meet-flutter-sdk#98]
Hello.

I live in a region of the world where the connection is quite weak. **So, is it possible to use "**JitSi**" to use it without an internet connection instead of an internet requirement ???**

If yes, please, what are all the configurations to do to successfully use "**JitSi**" without internet and efficiently???
Thanks in advance.

**Comment by saghul** [comment]
His topic is better suited for our community forum, this is the Flutter SDK repo...
